
DELETE http://localhost:9500/awesome-names

###

PUT http://localhost:9500/awesome-names
content-type: application/json

{
  "mappings": {
    "dynamic": false,
    "properties": {
      "id": {
        "type": "keyword"
      },
      "title": {
        "type": "text"
      }
    }
  }
}

###

POST http://localhost:9500/_bulk
content-type: application/json

< ./bulk-content
